compatibility_date = "2022-05-12"
main = "src/index.ts"
name = "doh-cache-worker-cf"
send_metrics = false
usage_model = "bundled"

[vars]
DOH_ENDPOINT = "[\"https://doh.opendns.com/dns-query\",\"https://dns.google/dns-query\",\"https://doh.pub/dns-query\",\"https://pngwczx94z.cloudflare-gateway.com/dns-query\"]"
DOH_PATHNAME = "/"
[observability]
[observability.logs]
enabled = true
invocation_logs = true